### PR TITLE
^3.0

### PR DESCRIPTION
**Pull request by marcemira**

### CODE REVIEW

**Comment by LaurentMarquet** [comment]
Hi,
is there a reason why it doesn't support Symfony 3.0.3 ? Apart from composer.json side.

**Comment by marcemira** [comment]
@Laurent3170 it actually works for ^3.0, I should change that title :grin:

**Comment by LaurentMarquet** [comment]
Thanks.
It seems not. If I do `composer require marcemira/bot-detect-bundle` I receive
Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - Installation request for marcemira/bot-detect-bundle ^3.0 -> satisfiable by marcemira/bot-detect-bundle[v3.0.0].
    - Conclusion: remove symfony/symfony v3.0.3
    - Conclusion: don't install symfony/symfony v3.0.3
    - marcemira/bot-detect-bundle v3.0.0 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3].
    - don't install symfony/security-bundle v2.3.0|don't install symfony/symfony v3.0.3
    - etc.
```

**Comment by marcemira** [comment]
@Laurent3170, try using `"marcemira/bot-detect-bundle": "dev-master"` and if that doesn't work either, you can just add `"symfony/security-bundle": "dev-master as 2.1"` in your composer.json. That is not certainly the best way of doing it, but it will work.

**Comment by LaurentMarquet** [comment]
Ok, I'll try and let you know.
Thanks

**Comment by LaurentMarquet** [comment]
So I hve used  "marcemira/bot-detect-bundle": "dev-master" and it worked!
Now I have to set-it up :smile: 
Thanks

**Comment by marcemira** [comment]
@Laurent3170 np ^^ It'll be better to create a new release tag with current master so you don't have to use dev-master. Cheers

**Comment by LaurentMarquet** [comment]
Ok, but don't mind for me. As I can't make it worked, I have developed a small function against a list of known bots, so I won't use it. But thanks anyway

**Pull request merged**
